Add TrieScanPrune operator
knowsys/nemo pull request #187
Opened 2023-04-19 15:46 UTC by rlwww

2023-04-20 19:24 UTC, mmarx reviewed
I have two questions, but the rest looks good!

2023-04-20 19:24 UTC, mmarx commented on src/physical/columnar/operations/columnscan_prune.rs
> +    /// Constructs a new column scan. This should not be called directory, but only by `TrieScanPrune`
`directory` -> “directly”?

2023-04-20 19:24 UTC, mmarx commented on src/physical/columnar/operations/columnscan_prune.rs
> +        }
isn't this just `self.find(|next_value| next_value >= minimum_value)`?

2023-04-21 05:55 UTC, monsterkrampe requested changes
Not sure if this really works but I think in some places one could replace `unsafe` blocks by calls to `get_mut` on `UnsafeCell`s since one already has a mutable reference to them anyway.

2023-04-21 05:55 UTC, monsterkrampe commented on src/physical/columnar/operations/columnscan_prune.rs
> +        unsafe { (*self.state.get()).get_next_value(self.column_scan_index) };
Since you have `&mut self` couldn't you do `self.state.get_mut().get_next_value(...)` without the `unsafe` block? Maybe I'm missing something.

2023-04-21 05:55 UTC, monsterkrampe commented on src/physical/tabular/operations/triescan_prune.rs
> +        unsafe { &mut *scan.get() }.current()
Again, since you get `&mut self`, couldn't you use `get_mut` on the `UnsafeCell` without the `unsafe` block?
(Same comment for the method below.)

2023-04-21 05:55 UTC, monsterkrampe commented on src/physical/tabular/operations/triescan_prune.rs
> +            (*self.state.get()).external_up();
Again, `get_mut` might help getting rid of the `unsafe` block. (Same in methods below.)

2023-05-09 10:06 UTC, mmarx commented
It's also already fixed on `main`, so just rebasing should get rid of it.

2023-05-09 21:19 UTC, mmarx requested changes
Found a typo in the docs, looks good otherwise!

2023-05-15 11:23 UTC, mmarx approved these changes

2023-05-15 11:27 UTC, merged