WIP: start decoupling csv reading from phys layer
knowsys/nemo pull request #222
Opened 2023-05-05 17:17 UTC by monsterkrampe

2023-05-06 12:08 UTC, monsterkrampe commented
@ellmau you can take over from here.
Everything seems to work as intended. I'm not sure if all the lifetime madness is really necessary; maybe this can be simplified.
Also, the things from `io` should probably distributed to the physical and the logical layer. I think this should be possible with the current implementations.
I also did not check the performance of CSV reading.

2023-05-09 09:39 UTC, ellmau commented
> As a follow up step, one could bring back the proper term parsing for the `Any` type and introduce an additional `String` type. But I think that this is out of scope of this PR.

I think so too, we should try to have smaller PRs anyway.

2023-05-09 22:07 UTC, mmarx requested changes
Looks good, just a small simplification

2023-05-09 22:07 UTC, mmarx commented on src/logical/execution/execution_engine.rs
> +                        .unwrap_or_else(|| (0..arity).map(|_| LogicalTypeEnum::Any).collect());
```rust
                    .unwrap_or_else(|| vec![LogicalTypeEnum::Any; *arity]),
```

2023-05-10 12:14 UTC, mmarx approved these changes

2023-05-10 12:22 UTC, merged