Data value api
knowsys/nemo pull request #242
Opened 2023-05-24 16:29 UTC by matzemathics

Adds the possibility for an `ExecutionEngine` to return an Iterator over Vecs of DataStorageValues. Also gets rid of the specialized `TrieRecords` struct, which can now be implemented by TrieScanPrune.

2023-05-24 16:33 UTC, mmarx commented
This is based on top of #241, right?

2023-05-24 16:36 UTC, matzemathics commented
> This is based on top of #241, right?

Yes.

2023-05-24 16:43 UTC, matzemathics commented
As requested in today's meeting, I also changed the API to return the output predicates seprately from reasoning, this also means
- it is now possible to call write without reason (which would just create empty files)
- reason is just another name for `ExecutionEngine::execute`

2023-05-26 11:58 UTC, mmarx requested changes
A few nits to pick with the doc comments, looks good otherwise.

Please rebase on top of `main` and/or #220.

2023-05-26 11:58 UTC, mmarx commented on src/api.rs
> +//! use nemo::api::{load,reason,output_predicates,write};
Please fix the formatting for the example (I realise it was already broken before, but there should be a space after each comma).

2023-05-26 11:58 UTC, mmarx commented on src/api.rs
> +/// Get a [`Vec`] of all output predicates, that are computed by the engine.
Drop the comma.

2023-05-26 11:58 UTC, mmarx commented on src/api.rs
>  /// If there have been `@source` routines in the parsed rules, all relative paths are resolved with the current working directory
Could you please replace `have been` with `are` (again, this was broken before, but please don't leave it this way)?

2023-05-26 11:58 UTC, mmarx commented on src/physical/dictionary/value_serializer.rs
> +/// by virtue of the schema index, a value appears at (inside a table).
replace the comma with `that`

2023-05-28 10:06 UTC, mmarx approved these changes

2023-05-28 10:06 UTC, merged