Feature/272 variable comparisons
knowsys/nemo pull request #276
Opened 2023-06-21 14:37 UTC by aannleax

Implements comparison operations between variables, i.e. you can now write `?X < ?Y` in the rule body. It should now also handle multiple comparisons correctly (before, writing `?X < 4` and `?X < 8` resulted in the first restriction being ignored).

This functionality has been implemented by extending `ColumnScanEqualValue` which has now been renamed to `ColumnScanRestrictValues` (and similar for the associated trie scan).

2023-06-21 23:17 UTC, mmarx requested changes
Just some small comments, looks good otherwise!

2023-06-21 23:17 UTC, mmarx commented on nemo-physical/src/columnar/operations/columnscan_restrict_values.rs
> +/// Concrete value a interval bound can take.
`an interval`

2023-06-21 23:17 UTC, mmarx commented on nemo-physical/src/columnar/operations/columnscan_restrict_values.rs
> +        }
Please use an explicit `match`, so we will not silently do the wrong thing when a new variant is added to the enum.

2023-06-21 23:17 UTC, mmarx commented on nemo-physical/src/columnar/operations/columnscan_restrict_values.rs
> +        }
see above

2023-06-21 23:17 UTC, mmarx commented on nemo-physical/src/tabular/operations/triescan_select.rs
> +                            };
Use `column_map.entry(*bound_index).or_insert_with(|| …)`

2023-06-22 07:20 UTC, aannleax commented on nemo-physical/src/util.rs
> +// pub mod interval;
Code there is not used anymore. I'll leave the file but remove the commented out module statement.

2023-06-22 12:36 UTC, mmarx commented on nemo-physical/src/util.rs
> -pub mod interval;
Still better than having dead code that is not compiled, so we will never know when it breaks ;)

2023-06-22 12:36 UTC, mmarx approved these changes

2023-06-22 12:47 UTC, merged