fix normalisation leading to invalid rules
knowsys/nemo pull request #358
Opened 2023-09-14 17:44 UTC by matzemathics

Fixes a bug discovered in #355 and generally tries to clean up the normalization code.

2023-09-14 19:44 UTC, mmarx requested changes
Looks good, just have a typo and one panic that could be worded slightly more precisely.

2023-09-14 19:44 UTC, mmarx commented on nemo/src/model/rule_model/aggregate.rs
> +            panic!("cannot substitute existential variable")
maybe be slightly more explicit and have `cannot substitute with existential variable` here?

2023-09-14 21:54 UTC, mmarx approved these changes

2023-09-15 09:50 UTC, aannleax approved these changes
Very nice

2023-09-15 10:08 UTC, merged