Add basic aggregate support
knowsys/nemo pull request #365
Opened 2023-09-20 17:34 UTC by rlwww

2023-09-21 08:30 UTC, mmarx requested changes
Looks good, just a few typos and some questions.

2023-09-21 08:30 UTC, mmarx commented on nemo/src/model/types/error.rs
> +    #[error("Aggregate operation \"{0:?}\" on input variable \"{1}\" requires a numerical input type, but was input type was \"{2}\".")]
`but was input type was` ;)

2023-09-21 08:30 UTC, mmarx commented on nemo/src/model/chase_model/aggregate.rs
> +    #[allow(missing_docs)]
Why no docs here?

2023-09-21 14:16 UTC, monsterkrampe commented on nemo-physical/src/aggregates/processors/processor.rs
> +    fn finish(&self) -> Option<StorageValueT>;
General Question: Shouldn't the aggregates work with `DataValueT`, or put differently: Do we not want to support aggregates on strings?

2023-09-21 17:46 UTC, mmarx approved these changes

2023-09-22 05:49 UTC, monsterkrampe approved these changes

2023-09-22 05:52 UTC, monsterkrampe commented on nemo-physical/src/aggregates/processors/processor.rs
> +    fn finish(&self) -> Option<StorageValueT>;
I'm aware that it's not easy to talk about `DataValueT` in a `TrieScan`. Intuitively, I feel that aggregation should happen on a higher level (but performance will suffer from that). Anyway, for now it should be fine :)

2023-09-22 10:03 UTC, aannleax requested changes
Very nice work :)

2023-10-03 14:10 UTC, merged