Tracing playground new data model adjustments
knowsys/nemo pull request #456
Opened 2024-03-27 15:39 UTC by monsterkrampe

This PR contains two features regarding tracing (that we also have for version `0.4.0` on the `tracing-playground` branch):
- read facts to be traced from file
- output GraphML format for trace result (required by Evonne)

2024-03-27 15:40 UTC, monsterkrampe commented
(I will rebase this again once the build on main has been fixed.)

2024-03-28 08:20 UTC, aannleax requested changes
Very cool :)

Have some minor comments

2024-03-28 08:20 UTC, aannleax commented on nemo-cli/src/cli.rs
> +    /// Specify an input file for the facts that should be explained
I would give a hint here about the expected input format

2024-03-28 08:20 UTC, aannleax commented on nemo-cli/src/main.rs
> +                                    log::warn!("!Warning: {err}");
This should probably result in an error

2024-03-28 08:20 UTC, aannleax commented on nemo/src/execution/tracing/trace.rs
> +    fn to_instantiated_rule(&self) -> Rule {
Would be nice to have a doc comment also for the private methods.

2024-03-28 13:11 UTC, aannleax approved these changes
Looks good, thanks :)

2024-03-28 14:59 UTC, merged